redis_uri: "redis://127.0.0.1:6379"
application:
  port: 8000
  hmac_secret: ""
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: ""
  authorization_token: ""
  timeout_millseconds: 10000
